# Generated by Django 3.1.6 on 2021-02-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Console',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('console_name', models.CharField(max_length=30)),
                ('pod_location', models.CharField(choices=[('0', 'Networking Lab'), ('1', 'Datacenter')], max_length=1)),
                ('console_note', models.CharField(max_length=100)),
            ],
        ),
    ]
