# Generated by Django 3.1.6 on 2021-02-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_console_pod_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='console',
            name='console_ip_address',
            field=models.CharField(default='1.1.1.1', max_length=11),
        ),
        migrations.AlterField(
            model_name='console',
            name='console_note',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='console',
            name='pod_location',
            field=models.IntegerField(default=0),
        ),
    ]
