# Generated by Django 3.1.6 on 2021-02-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210228_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='console',
            name='console_delete_note',
            field=models.CharField(default='', max_length=100),
        ),
    ]
