# Generated by Django 3.1.6 on 2021-03-01 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_console_console_delete_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='console',
            name='console_delete_note',
        ),
    ]
