# Generated by Django 3.1.6 on 2021-03-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_console_console_delete_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=30)),
                ('pod_location', models.IntegerField(default=0)),
                ('pod_number', models.IntegerField(default=0)),
                ('device_ip_address', models.CharField(default='1.1.1.1', max_length=11)),
                ('device_mac_address', models.CharField(default='FF:FF:FF:FF:FF:FF', max_length=17)),
                ('device_note', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
