# Generated by Django 3.1.6 on 2021-03-07 18:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scripts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('script_name', models.CharField(max_length=30)),
                ('script_version', models.FloatField(default=1.0)),
                ('device_type', models.IntegerField(default=0)),
                ('pod_location', models.IntegerField(default=0)),
                ('script_note', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
