# Generated by Django 3.1.6 on 2021-03-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_scripts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scripts',
            name='pod_location',
        ),
        migrations.AddField(
            model_name='scripts',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scripts',
            name='script_file',
            field=models.FileField(default='scripts/', upload_to='scripts/<django.db.models.fields.UUIDField>/'),
        ),
    ]
