# Generated by Django 3.1.6 on 2021-03-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210310_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scripts',
            name='script_uuid',
        ),
        migrations.AlterField(
            model_name='scripts',
            name='script_file',
            field=models.FileField(default='scripts/', upload_to='scripts/'),
        ),
    ]
