# Generated by Django 3.1.6 on 2021-03-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210315_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='scripts',
            name='script_ext',
            field=models.CharField(default='txt', max_length=10),
        ),
        migrations.AddField(
            model_name='scripts',
            name='script_size',
            field=models.IntegerField(default=0),
        ),
    ]
