# Generated by Django 3.1.6 on 2021-03-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210315_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scripts',
            name='script_ext',
            field=models.CharField(default='txt', max_length=100),
        ),
        migrations.AlterField(
            model_name='scripts',
            name='script_size',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
