# Generated by Django 3.1.6 on 2021-03-17 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210317_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scripts',
            name='script_size',
        ),
    ]
