# Generated by Django 3.1.6 on 2021-03-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_scripts_script_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scripts',
            name='script_ext',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
